name: Test and Build
on:
  pull_request:
    branches:
      - master

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Client Dependencies
        run: npm --prefix ./client install ./client
      # - name: Test
      #   run: CI=true npm test
      - name: Build
        run: npm --prefix ./client run build ./client
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: client/build
